//  Converted to Swift 5 by MindDoc - https://minddoc.de
//
//  TCHError.swift
//  Twilio Chat Client
//
//  Copyright (c) 2018 Twilio, Inc. All rights reserved.
//

import Foundation

/** Twilio Chat error object 

 TCHError is a descendent of NSError.  The Chat Client will populate the following properties for most errors:

 - domain - Will be equivalent to the constant pointed to by TCHErrorDomain
 - code - Will be a numeric code indicating the failure or TCHErrorGeneric for errors generated by the client locally
 - userInfo[TCHErrorMsgKey] - May contain an optional string representation of the error with more detail if available
 */

open class TCHError: NSError {
}
