version: 2
jobs:
  lint:
    docker:
    - image: norionomura/swiftlint:0.34.0_swift-5.0.2
    steps:
      - checkout
      - run:
          name: Lint swift package
          command: swiftlint
  test:
    docker:
    - image: swift:5.0.2
    steps:
      - checkout
      - run:
          name: Test swift package
          command: swift test
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test
